# Generated by Django 5.1.6 on 2025-07-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosyaEk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosyaekmodel',
            name='dosyaUzantisi',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
