# Generated by Django 5.1.6 on 2025-07-24 08:07

import dosyaEk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosyaEk', '0002_dosyaekmodel_dosyauzantisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosyaekmodel',
            name='dosya',
            field=models.FileField(upload_to='dosyalar/', validators=[dosyaEk.models.validateFileExtension]),
        ),
    ]
