# Generated by Django 5.1.6 on 2025-07-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaporModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=150)),
                ('aciklama', models.CharField(max_length=150)),
                ('raporOlusturmaTarihi', models.DateTimeField(auto_now_add=True)),
                ('raporDuzenlemeTarihi', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
