# Generated by Django 5.1.6 on 2025-07-18 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dosyaEk', '0001_initial'),
        ('gorselEk', '0001_initial'),
        ('raporApp', '0001_initial'),
        ('revizeApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rapormodel',
            name='RaporDuzenleyen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raporDuzenleyen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rapormodel',
            name='raporDosya',
            field=models.ManyToManyField(blank=True, related_name='raporDosyalar', to='dosyaEk.dosyaekmodel'),
        ),
        migrations.AddField(
            model_name='rapormodel',
            name='raporOlusturan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raporOlusturan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rapormodel',
            name='raporResim',
            field=models.ManyToManyField(blank=True, related_name='raporResimler', to='gorselEk.gorselekmodel'),
        ),
        migrations.AddField(
            model_name='rapormodel',
            name='raporRevize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revizeApp.revizemodel'),
        ),
    ]
