# Generated by Django 5.1.6 on 2025-07-18 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raporApp', '0002_initial'),
        ('revizeApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapormodel',
            name='raporRevize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raporRevize', to='revizeApp.revizemodel'),
        ),
    ]
