# Generated by Django 5.1.6 on 2025-08-05 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raporApp', '0003_alter_rapormodel_raporrevize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rapormodel',
            old_name='RaporDuzenleyen',
            new_name='raporDuzenleyen',
        ),
    ]
