# Generated by Django 5.1.6 on 2025-08-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raporApp', '0004_rename_raporduzenleyen_rapormodel_raporduzenleyen'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapormodel',
            name='revizeDurumu',
            field=models.CharField(choices=[('revizeRaporBekleniyor', 'Revize Rapor Bekleniyor'), ('revizeOnayBekleniyor', 'Revize Onay Bekleniyor')], default='Revize Rapor Bekleniyor.', max_length=50),
        ),
    ]
