# Generated by Django 5.1.6 on 2025-08-06 06:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raporApp', '0005_rapormodel_revizedurumu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rapormodel',
            name='revizeDurumu',
        ),
        migrations.AddField(
            model_name='rapormodel',
            name='raporKullanicilar',
            field=models.ManyToManyField(blank=True, related_name='raporKullanicilar', to=settings.AUTH_USER_MODEL),
        ),
    ]
