# Generated by Django 5.1.6 on 2025-07-18 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dosyaEk', '0001_initial'),
        ('gorevApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=150)),
                ('aciklama', models.CharField(max_length=350)),
                ('revizeOlusturmaTarihi', models.DateTimeField(auto_now_add=True)),
                ('revizeDuzenlemeTarihi', models.DateTimeField(auto_now=True)),
                ('gorev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gorevApp.gorevmodel')),
                ('revizeDosya', models.ManyToManyField(blank=True, related_name='revizeDosyalar', to='dosyaEk.dosyaekmodel')),
            ],
        ),
    ]
