# Generated by Django 5.1.6 on 2025-07-18 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gorselEk', '0001_initial'),
        ('revizeApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='revizemodel',
            name='revizeDuzenleyen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revizeDuzenleyenler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revizemodel',
            name='revizeKullanicilar',
            field=models.ManyToManyField(blank=True, related_name='revizeKullanicilar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revizemodel',
            name='revizeOlusturan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revizeOlusturanlar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revizemodel',
            name='revizeResim',
            field=models.ManyToManyField(blank=True, related_name='revizeResimler', to='gorselEk.gorselekmodel'),
        ),
    ]
