# Generated by Django 5.1.6 on 2025-07-21 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revizeApp', '0003_alter_revizemodel_gorev'),
    ]

    operations = [
        migrations.AddField(
            model_name='revizemodel',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='revizemodel',
            name='oncekiRevize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='altRevize', to='revizeApp.revizemodel'),
        ),
    ]
