# Generated by Django 5.1.6 on 2025-08-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revizeApp', '0004_revizemodel_aktif_revizemodel_oncekirevize'),
    ]

    operations = [
        migrations.AddField(
            model_name='revizemodel',
            name='RevizeDurumu',
            field=models.CharField(choices=[('revizeRaporBekleniyor', 'Revize Rapor Bekleniyor'), ('revizeIptal', 'Revize İptal'), ('revizeOnayBekleniyor', 'Revize Onay Bekleniyor'), ('revizeOnaylandı', 'Revize Onaylandı')], default='Revize Rapor Bekleniyor.', max_length=50),
        ),
    ]
