# Generated by Django 5.1.6 on 2025-08-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revizeApp', '0005_revizemodel_revizedurumu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revizemodel',
            old_name='RevizeDurumu',
            new_name='revizeDurumu',
        ),
    ]
