# Generated by Django 5.1.6 on 2025-08-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revizeApp', '0006_rename_revizedurumu_revizemodel_revizedurumu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revizemodel',
            name='revizeDurumu',
            field=models.CharField(choices=[('revizeRaporBekleniyor', 'Revize Rapor Bekleniyor'), ('revizeIptal', 'Revize İptal'), ('revizeGuncellendi', 'Revize Güncellendi'), ('revizeOnayBekleniyor', 'Revize Onay Bekleniyor'), ('revizeOnaylandı', 'Revize Onaylandı')], default='Revize Rapor Bekleniyor.', max_length=50),
        ),
    ]
