# Generated by Django 5.1.6 on 2025-08-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revizeApp', '0007_alter_revizemodel_revizedurumu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revizemodel',
            name='revizeDurumu',
            field=models.CharField(choices=[('revizeRaporBekleniyor', 'Revize Rapor Bekleniyor'), ('revizeIptal', 'Revize İptal'), ('revizeGuncellendi', 'Revize Güncellendi'), ('revizeOnayBekleniyor', 'Revize Onay Bekleniyor'), ('revizeOnaylandi', 'Revize Onaylandı')], default='Revize Rapor Bekleniyor.', max_length=50),
        ),
    ]
