# Generated by Django 5.2.4 on 2025-07-24 08:12

import videoEk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoEkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videolar/', validators=[videoEk.models.validateVideoExtensions])),
                ('videoYuklenmeTarihi', models.DateTimeField(auto_now_add=True)),
                ('videoUzantisi', models.CharField(blank=True, max_length=15)),
            ],
        ),
    ]
