# Generated by Django 5.2.4 on 2025-07-24 08:41

import videoEk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoEk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoekmodel',
            name='video',
            field=models.FileField(upload_to='videolar/', validators=[videoEk.models.validateVideoExtensions, videoEk.models.validateVideoSize]),
        ),
    ]
