# Generated by Django 5.1.6 on 2025-07-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GorselEkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(upload_to='resimler/')),
                ('resimOlusturmaTarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
