# Generated by Django 5.1.6 on 2025-07-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gorselEk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gorselekmodel',
            name='resimUzantisi',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
