# Generated by Django 5.1.6 on 2025-07-24 08:07

import gorselEk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gorselEk', '0002_gorselekmodel_resimuzantisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gorselekmodel',
            name='resim',
            field=models.ImageField(upload_to='resimler/', validators=[gorselEk.models.ValidateImageExtencions]),
        ),
    ]
