# Generated by Django 5.2.4 on 2025-07-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneSignalApiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ONESIGNAL_APP_ID', models.CharField(max_length=255)),
                ('ONESIGNAL_API_KEY', models.CharField(max_length=255)),
            ],
        ),
    ]
