# Generated by Django 5.2.4 on 2025-07-24 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificationsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onesignalapimodel',
            old_name='ONESIGNAL_API_KEY',
            new_name='oneSignalApiId',
        ),
        migrations.RenameField(
            model_name='onesignalapimodel',
            old_name='ONESIGNAL_APP_ID',
            new_name='oneSignalApiKey',
        ),
    ]
