# Generated by Django 5.1.6 on 2025-07-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dosyaEk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GorevModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=150)),
                ('aciklama', models.CharField(max_length=350)),
                ('gorevOlusturmaTarihi', models.DateTimeField(auto_now_add=True)),
                ('gorevDuzenlemeTarihi', models.DateTimeField(auto_now=True)),
                ('gorevDurumu', models.CharField(choices=[('raporBekleniyor', 'Rapor bekleniyor'), ('iptal', 'İptal'), ('onayBekleniyor', 'Onay bekleniyor'), ('onaylandı', 'Onaylandı')], default='Rapor bekleniyor.', max_length=50)),
                ('gorevDosya', models.ManyToManyField(blank=True, related_name='dosyalar', to='dosyaEk.dosyaekmodel')),
            ],
        ),
    ]
