# Generated by Django 5.1.6 on 2025-07-18 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gorevApp', '0001_initial'),
        ('gorselEk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gorevmodel',
            name='gorevDuzenleyen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gorevDuzenleyen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gorevmodel',
            name='gorevOlusturan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gorevOluşturan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gorevmodel',
            name='gorevResim',
            field=models.ManyToManyField(blank=True, related_name='resimler', to='gorselEk.gorselekmodel'),
        ),
        migrations.AddField(
            model_name='gorevmodel',
            name='gorevliler',
            field=models.ManyToManyField(blank=True, related_name='görevliler', to=settings.AUTH_USER_MODEL),
        ),
    ]
