# Generated by Django 5.1.6 on 2025-08-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gorevApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gorevmodel',
            name='gorevDurumu',
            field=models.CharField(choices=[('gorevAtandı', 'Gorev Atandı.'), ('gorevIptal', 'Görev İptal'), ('gorevOnayBekleniyor', 'Görev Onay Bekleniyor'), ('gorevOnaylandı', 'Görev Onaylandı')], default='Gorev Atandı.', max_length=50),
        ),
    ]
