# Generated by Django 5.1.6 on 2025-08-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gorevApp', '0007_alter_gorevmodel_gorevdurumu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gorevmodel',
            name='gorevDurumu',
            field=models.CharField(choices=[('gorevAtandi', 'Gorev Atandı.'), ('gorevIptal', 'Görev İptal'), ('gorevOnayBekleniyor', 'Görev Onay Bekleniyor'), ('gorevOnaylandi', 'Görev Onaylandı')], default='Görev Atandı', max_length=50),
        ),
    ]
