# Generated by Django 5.2.4 on 2025-07-24 08:31

import sesEk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SesEkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ses', models.FileField(upload_to='ses/', validators=[sesEk.models.validateSesExtensions])),
                ('sesYuklenmeTarihi', models.DateTimeField(auto_now_add=True)),
                ('sesUzantisi', models.CharField(blank=True, max_length=15)),
            ],
        ),
    ]
